# Generated by Django 3.1 on 2022-03-13 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0004_auto_20211020_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(default='No instructions have been given.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.TextField(blank='https://www.youtube.com/embed/NpEaa2P7qZI'),
        ),
    ]
